### ISSUE TITLE
Time in smart app incorrect

### ISSUE THREAD

**Issue by Hans-Nouwens** [Geonovum/smartemission#101]
Time shown in smart app is not right.
'+2 hours' is not necessary 
![smart app verkeerde tijd](https://user-images.githubusercontent.com/36516784/38085601-6f59e628-3351-11e8-9ace-45b2048b7e1a.png)

**Comment by justb4** [comment]
Well, the time, here 12:56:58 should be correct. The +02:00 denotes the offset from GMT/UTC including daylight savings. 12:56:58+02:00  is the standard [ISO 8601 ](https://en.wikipedia.org/wiki/ISO_8601) notation.

**Comment by Hans-Nouwens** [comment]
For inhabitants the notation is not clear:
Laatste  Meting  2018-03-29 12:56:58+02:00

**Comment by Hans-Nouwens** [comment]
Just er is iets niet juist in de tijdsaanduiding:
Bij een actuele tijd van 17:03 geven de units 17:03 +2 uur aan

**Comment by justb4** [comment]
Tijdaanduiding is juist: 17:03 +2 uur betekent: 17:03 met een offset +2 van UTC/GMT. Dus UTC is dan 15:03. 17:03 is "onze" NL tijd. Die +2 is niets meer dan een aanduiding, net als CET etc, alleen exacter omdat o.a Daylight Savings wordt meegenomen.

**Comment by Hans-Nouwens** [comment]
Hoewel volgens ISO een juiste beschrijving is, is het voor niet ingewijden onlogisch gezien de reacties hierop.
Dat het UTC +2 is, is onduidelijk omdat UTC nergens staat.

Ik vraag me af: Wat is het belangrijkste: volgens de regels juist of begrijpelijk voor de gebruiker?

Mij maakt het verder niet uit. Het is alleen verwarrend. Mocht je het niet aan kunnen/willen passen, dan laten we het zo.

**Comment by justb4** [comment]
Laat maar even open, op SCLL heb ik geen budget momenteel, als ze er in ["SE Nijmegen Project" ](https://github.com/Geonovum/smartemission/projects/1) last van hebben kan het mogelijk via dat project.

**Comment by justb4** [comment]
Bleek ook lastig bij PDOK migratie, dus aangepast. SmartApp herladen. Tijd moet iets geven als: 
`10-4-2018 om 15:06:24 NL`.

**Comment by Hans-Nouwens** [comment]
Hei Just,

 

Laatste meting is nu leeg

 

Van: Just van den Broecke <notifications@github.com> 
Verzonden: dinsdag 10 april 2018 15:10
Aan: Geonovum/smartemission <smartemission@noreply.github.com>
CC: Hans-Nouwens <hans@slimstestad.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Geonovum/smartemission] Time in smart app incorrect (#101)

 

Bleek ook lastig bij PDOK migratie, dus aangepast. SmartApp herladen. Tijd moet iets geven als:
10-4-2018 om 15:06:24 NL.

**Comment by Hans-Nouwens** [comment]
Safari

Met groet, Hans Nouwens

**Comment by justb4** [comment]
Zou nu goed moeten zijn, althans in Chrome+Safari+Firefox ok, IE heb ik niet.

**Comment by Hans-Nouwens** [comment]
Chrome en Safari geven bij mij nog geen waarde bij laatste meting

 

Van: Just van den Broecke <notifications@github.com> 
Verzonden: dinsdag 10 april 2018 15:10
Aan: Geonovum/smartemission <smartemission@noreply.github.com>
CC: Hans-Nouwens <hans@slimstestad.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Geonovum/smartemission] Time in smart app incorrect (#101)

 

Bleek ook lastig bij PDOK migratie, dus aangepast. SmartApp herladen. Tijd moet iets geven als:
10-4-2018 om 15:06:24 NL.

**Comment by justb4** [comment]
vreemd, browser caching? shift reload.

**Comment by Hans-Nouwens** [comment]
Werkt!

 

Van: Just van den Broecke <notifications@github.com> 
Verzonden: dinsdag 10 april 2018 20:58
Aan: Geonovum/smartemission <smartemission@noreply.github.com>
CC: Hans-Nouwens <hans@slimstestad.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [Geonovum/smartemission] Time in smart app incorrect (#101)

 

vreemd, browser caching? shift reload.
