### ISSUE TITLE
Direct (WFS) geen actuele gegevens?

### ISSUE THREAD

**Issue by RG-Dordrecht** [Geonovum/smartemission#106]
Bij het uitlezen van de onderstaande WFS krijgen we data door tot en met 27 maart. Graag zouden we de data tot en met vandaag willen uitlezen. Bij eerdere uitlees-acties werkte dit probleemloos. Wat is ervoor nodig om weer de meest actuele gegevens ook uit te kunnen lezen? 

Direct (WFS)
For raw/direct download via your browser or a download tool like curl, a quick WFS download be done this base URL:
http://data.smartemission.nl/geoserver/wfs?request=GetFeature&typename=timeseries_component&outputformat=csv&CQL_FILTER=device_id=station id

**Comment by justb4** [comment]
het bleek dat de dataverwerking sinds 27 maart per ongeluk was stopgezet. deze is nu weer aangezet. zal plm 24 uur duren voordat alle data weer "bij" is.
