### ISSUE TITLE
WFS niet up to date

### ISSUE THREAD

**Issue by RG-Dordrecht** [Geonovum/smartemission#109]
Onlangs onderstaand bericht (issue 106) gepost over het ontbreken van meest actuele gegevens. 
De WFS is nu ten dele bijgewerkt. Echter komt nu data door tot slechts 05-04-2018 03.00. Opnieuw de vraag wat er voor nodig is om weer de meest actuele gegevens ook uit te kunnen lezen?

RG-Dordrecht  commented 5 days ago 

Bij het uitlezen van de onderstaande WFS krijgen we data door tot en met 27 maart. Graag zouden we de data tot en met vandaag willen uitlezen. Bij eerdere uitlees-acties werkte dit probleemloos. Wat is ervoor nodig om weer de meest actuele gegevens ook uit te kunnen lezen?

Direct (WFS)
 For raw/direct download via your browser or a download tool like curl, a quick WFS download be done this base URL:
http://data.smartemission.nl/geoserver/wfs?request=GetFeature&typename=timeseries_component&outputformat=csv&CQL_FILTER=device_id=station id
 

  Contributor This user has previously committed to the smartemission repository. 
justb4  commented 5 days ago 

het bleek dat de dataverwerking sinds 27 maart per ongeluk was stopgezet. deze is nu weer aangezet. zal plm 24 uur duren voordat alle data weer "bij" is.

**Comment by justb4** [comment]
Zou nu weer "bij" moeten zijn.

**Comment by RG-Dordrecht** [comment]
Dank voor de inspanningen!

Verstuurd vanaf mijn iPhone

Op 10 apr. 2018 om 13:40 heeft Just van den Broecke <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Zou nu weer "bij" moeten zijn.
