### ISSUE TITLE
Meteen inzoomen op sensor via link smartapp

### ISSUE THREAD

**Issue by bdg-intemo** [Geonovum/smartemission#13]
Is het mogelijk om met een directe link per sensor direct in de smartapp in te zoomen (en de sensorinfo te openen) op de sensor waar de link van is?

**Comment by justb4** [comment]
Ok, in URL kan parameter "station" worden meegegeven. Indien dit een bestaand station is, opent popup/waarden alsof erop geklikt is, bijv:

http://test.smartemission.nl/smartapp?station=20

**Comment by bdg-intemo** [comment]
Bedankt!
