### ISSUE TITLE
Automatic creation of csv file of RIVM measurement at Graafseweg and Ruyterstraat

### ISSUE THREAD

**Issue by pietermarsman** [Geonovum/smartemission#19]
Columns: O3_Waarden, NO2_Waarden, CO_Waarden
Granularity: per hour (can be interpolated)
Maybe separate file per station

**Comment by justb4** [comment]
Same as for #18, my first comment: I can collect RIVM values in a table and generate CSV from that, also possibly via an online API like WFS. You can cache the CSVs from that service. May also be easier for testing than moving CSV-files around.

**Comment by pietermarsman** [comment]
Good idea!
