### ISSUE TITLE
Publiceren refined Jose waarden naar InfluxDB

### ISSUE THREAD

**Issue by justb4** [Geonovum/smartemission#31]
De Refiner (gecalibreerde uurwaarden) schrijft nu naar Postgis DB. Uitbreiden met ook naar InfluxDB schrijven. Kan via Grafana dan visueel met RIVM waarden harvested in ``rivm`` tabel  vergeleken. 

Moet simpel in Stetl ``refiner.cfg`` ETL  te doen zijn:

```
chains = input_raw_sensor_db| (refine_filter|output_postgres_insert) (refine_filter_small|output_influxdb_write)
```

In InfluxDB dan publiceren naar ``joserefined`` tabel.

**Comment by pietermarsman** [comment]
Volgens mij is dit gefixt toch?

**Comment by justb4** [comment]
Ja, over en sluiten..
