### ISSUE TITLE
Calibratie toevoegen aan laatste waarden 

### ISSUE THREAD

**Issue by pietermarsman** [Geonovum/smartemission#39]
Just: 

> de "last.sh, last.cfg" haalt live waarden op van WHale API (tbv
> SmartApp) op en roept direct de sensorconverters.py aan via
> sensordefs.py. Dus heeft niet de calibrator initialisatie en geeft
> foutmeldingen hierover.
>

**Comment by pietermarsman** [comment]
Extra probleem hierbij: de data wordt gefilterd in sensorconverters.py. Hier kan maar 1 proces gebruik van maken want er worden globale variabelen gebruikt.

**Comment by justb4** [comment]
Ja klopt, is historisch, ``last`` was er als eerste om wat te laten zien in SmartApp. Ik denk dat we ``sensorconverters.py`` het beste kunnen 'modulariseren' zodat deze o.a. zelf de modellen uit de DB ophaalt. Mogelijk kunnen de globale vars dan in class-instances. Dan kan ``sensorconverters.py`` ook los van Stetl aangeroepen worden.  Ik denk trouwens dat deze globals (en model-instantie) per Stel-proces uniek zijn (niet voor elkaar zichtbaar). Mogelijk ontstaan er ook geheugen problemen bij meerdere model-instanties(?). Maar laten we eerst de andere Stetl processen (alles behalve ``last``) op orde krijgen en dan 'modulariseren'.
