### ISSUE TITLE
SmartApp: JavaScript error bij sluiten info popup

### ISSUE THREAD

**Issue by justb4** [Geonovum/smartemission#4]
Zie plaatje hieronder

![err](https://cloud.githubusercontent.com/assets/582630/13573255/0c6a999a-e47f-11e5-9115-6276cf31009f.png)

Gebeurt bij sluiten van de popup die verschijnt na klikken op station.

**Comment by pietermarsman** [comment]
Ik kan deze error niet reproduceren.

**Comment by justb4** [comment]
Ik ook niet meer :-). Mogelijk heb ik deze toch gefixed. Sluiten en heropenen als ie terugkomt.
