### ISSUE TITLE
laagfrequent geluid

### ISSUE THREAD

**Issue by geurp0** [Geonovum/smartemission#5]
Burgers vragen om een aparte view op laagfrequent geluid. <25 DB

**Comment by bdg-intemo** [comment]
De sensor meet op dit moment nog geen laagfrequent geluid dus het heeft weinig zin om dat te visualiseren denk ik.

**Comment by justb4** [comment]
Dan voorlopig sluiten. @geurp0 : open voor andere wensen mbt geluid nieuw issue.
