### ISSUE TITLE
Gost onbekend tijdens init-databases.sh

### ISSUE THREAD

**Issue by pietermarsman** [Geonovum/smartemission#54]
`Error: No such object: gost`

Tijdens laden van `common.sh`.

Regel 21: 
`export STAHOST='sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' gost'`

Als deze regel wordt gecomment is er geen error.

**Comment by justb4** [comment]
overblijfsel, gost comm nu via Docker of host-specifiek URL
