### ISSUE TITLE
Sensor Jose-060 working properly but data is not seen in any viewer

### ISSUE THREAD

**Issue by Nijmegen-Geluid** [Geonovum/smartemission#62]
Please check why data is not seen in the viewers. Sensor Jose060 is connected!
Wifi network is connected to Wifi station GN-Extern in the building of the local goverment of Nijmegen.

**Comment by justb4** [comment]
http://whale.citygis.nl/sensors/v1/devices/60/last no data is received from Whale server for device 60,...

**Comment by justb4** [comment]
See timeseries for station 60:  no data available in Whale server since 30 jan 2017:
http://whale.citygis.nl/sensors/v1/devices/60/timeseries
Maybe @RobertKieboom can check further.

**Comment by Nijmegen-Geluid** [comment]
The same problem for the Sensor Jose063.
And is also connected by Wifi station GN-Extern.

**Comment by justb4** [comment]
Same story: no data received by Whale server: http://whale.citygis.nl/sensors/v1/devices/63/last

**Comment by Nijmegen-Geluid** [comment]
Sensor Jose-063 is working properly now.
But sensor Jose-060 is still not working. Hardware seems to work allright. But data is not shown in any viewer.

**Comment by justb4** [comment]
Sorry, but this is somehting @RobertKieboom can only verify (see above):
no data available in Whale server since 30 jan 2017:
http://whale.citygis.nl/sensors/v1/devices/60/timeseries

**Comment by justb4** [comment]
Sorry nothing we can do here to solve.
