### ISSUE TITLE
Geluidweergave klopt niet

### ISSUE THREAD

**Issue by Hans-Nouwens** [Geonovum/smartemission#89]
Getallen van de geluidweergave staat verkeerd:
Geluid
1 int           Niveau 33 van 5

Dit komt bij diverse sensoren binnen Nijmegen voor. Bijv Station 35

**Comment by justb4** [comment]
Confirmed: inkomende data is ok maar bij sommige stations wordt geluid in dB(A) en geluidsnivo verwisseld binnen app HTML. Wordt gefixed...

**Comment by justb4** [comment]
Fixed, closing issue.
