### ISSUE TITLE
SmartApp: Add color scheme to Air Quality values

### ISSUE THREAD

**Issue by geurp0** [Geonovum/smartemission#91]
The values of the Air-quality sensors don't make sense for the average user. Is it possible to add a colorscheme to the values indicating the quality of the value? Color scheme info to get at Henk Nijhuis

**Comment by justb4** [comment]
Ok, see also [issue 64 comment](https://github.com/Geonovum/smartemission/issues/64#issuecomment-341756593): these color scheme's are already implemented in Heron (via WMS SLDs) with SLDs from RIVM. 

I propose to use the same color schemes here, otherwise things may get confusing. 
But ok, can you attach the Nijmegen color scheme here?

This is the proposed simple 5-color scheme (from RIVM):

![image](https://user-images.githubusercontent.com/582630/32385295-edf5f6e0-c0bd-11e7-9b6f-8baf1b48dde6.png)

corresponding to:

![image](https://user-images.githubusercontent.com/582630/32385351-1ea5493a-c0be-11e7-8d95-34e9957ef322.png)

The SLDs use a more elaborate color scheme (from RIVM), see also https://www.luchtmeetnet.nl/uitleg#:

![image](https://user-images.githubusercontent.com/582630/32384902-ad40153c-c0bc-11e7-8c2b-3f5e8751f9ef.png)

**Comment by geurp0** [comment]
This colorscheme is ok. There is no Nijmegen schema :-)

**Comment by justb4** [comment]
Welk kleurenschema te gebruiken: met 5 kleuren, zoals:
![image](https://user-images.githubusercontent.com/582630/36433043-e8b1cd6e-165b-11e8-8e34-838f8ab93e33.png)
of met 11 zoals boven?

Voor eenvoud en begrijpelijkheid stel ik 5 kleuren voor.

**Comment by justb4** [comment]
@geurp0 begonnen, in eerste aanzet kan zo bijv weergegeven:

![image](https://user-images.githubusercontent.com/582630/36439132-384fdd10-166c-11e8-913b-8974203f4eec.png)

of zo

![image](https://user-images.githubusercontent.com/582630/36439172-55eee1ae-166c-11e8-8635-2345ef50def7.png)

Er zijn alleen kleurenschema's (van RIVM) voor NO2, O3, PM10 en PM2.5, niet voor CO en CO2, ook niet ergens kunnen vinden.

Er zal nog wel een legenda bij moeten, iets bedenken waar. Er gaat sowieso veel ruimte verloren aan logo's en plaatjes bovenin. Dat zou 1/2 tot 2/3 compacter kunnen.

**Comment by geurp0** [comment]
5 kleuren graag. Kijk maar wat je aan overhead kan verminderen.

Paul Geurts
Strategisch Adviseur Informatie Management
Gemeente Nijmegen
06 – 53678077
p.geurts@nijmegen.nl
bereikbaar op maandag, dinsdag, woensdag, vrijdag
________________________________

**Comment by geurp0** [comment]
Je zou locatie en laatste meting nog iets kleiner kunnen maken en dan 1 horizontale legenda maken die van slecht naar goed loopt. Dat kost ook niet zoveel ruimte. Idee?

Paul Geurts
Strategisch Adviseur Informatie Management
Gemeente Nijmegen
06 – 53678077
p.geurts@nijmegen.nl
bereikbaar op maandag, dinsdag, woensdag, vrijdag
________________________________

**Comment by justb4** [comment]
Ja goede suggestie. Het SE logo is ook wel erg breed. Zou mooi zijn om iets kleins vierkant te hebben zoals ik in  favicon (SE webapps) gebruik, bijv:

![image](https://user-images.githubusercontent.com/582630/36483766-597933d2-1717-11e8-8138-98ec12c554db.png)

Kan de ontwerper dat misschien doen? Het logo is nogal verwarrend ook: lijken net knoppen. Dit lijkt ook wat een smiley :-).
 
Wilde nog iets met een image rollover (hover) doen, maar wordt lastig met touch/mobiel.

Sowieso loop ik wat tegen het feit aan dat de SmartApp destijds ietwat quick & dirty is gebouwd...maar goed, kleuren en legenda moet gaan lukken.

**Comment by justb4** [comment]
@geurp0 heb de hele popup compacter gemaakt, en AQ kleuren+legenda toegevoegd:

![image](https://user-images.githubusercontent.com/582630/36506726-c022a812-1757-11e8-8bb2-6ba6749cf6cd.png)

of direct via http://data.smartemission.nl/smartapp (evt expliciet herladen ivm browser caching).

**Comment by geurp0** [comment]
Hoi just
Super gedaan. Heel intuïtief en geeft nu zoveel meer info.


Paul Geurts
Strategisch Adviseur Informatie Management
Gemeente Nijmegen
06 – 53678077
p.geurts@nijmegen.nl
bereikbaar op maandag, dinsdag, woensdag, vrijdag
________________________________

**Comment by justb4** [comment]
Kunnen we deze issue dan sluiten? Via ander issue zou ik graag een nieuw SE logo zien, zie issue #95.

**Comment by justb4** [comment]
Laatste wijziging: station nummer in popup heading en logo/SE naam vast rechtsboven in kaart, nog iets ruimte teruggewonnen..

![image](https://user-images.githubusercontent.com/582630/36564387-74107884-181d-11e8-9bf6-da9a6b904917.png)

**Comment by geurp0** [comment]
Deze kan gesloten worden.
