### ISSUE TITLE
Smart app toonde geen enkele unit meer, en nu geen met id boven 2000

### ISSUE THREAD

**Issue by Hans-Nouwens** [Geonovum/smartemission#97]
Vandaag, 28-2, was heel Nederland leeg volgens de smart app. Eerst vielen er enkele units met ID 2000xxxxx uit. Rond 19:30 waren alle units boven 2000 weg en rond 20:00 uur was er geen enkele unit meer te zien. Inmiddels zijn enkele units weer te zien maar geen van de units boven 2000.

Ook in de josene viewer van Intemo zijn alle units verdwenen. De kou kan het niet zijn want er staan enkele units binnen.

**Comment by justb4** [comment]
Was tijdelijk, platform kreeg idd geen data meer binnen van de Josene Data Collector. Alle stations zijn/lijken weer terug, dus sluiten.
